In [3]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
array1.shape # 배열 차원 : 1차원 배열

(11,)

In [5]:
type(array1) # 배열 타입: numpy array

numpy.ndarray

### numpy array를 만드는 다양한 방법
1. full (균일한 값으로 생성)
2. random (랜덤한 값으로 생성) / 모율 내 random 함수!
3. arange (연속된 값들로 생성)

In [10]:
# full : 균일한 값으로 생성
arr1 = np.full(6, 7)
arr2 = np.full(6, 0)
arr3 = np.zeros(6, dtype=int) # 모든 값이 0인 numpy array
arr4 = np.ones(6, dtype=int) # 모든 값이 1인 numpy array

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[7 7 7 7 7 7]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[1 1 1 1 1 1]


In [12]:
# random
arr1 = np.random.random(6)
arr2 = np.random.random(6)

print(arr1)
print(arr2)

[0.77969191 0.72276705 0.70139475 0.46536122 0.11155609 0.62423025]
[0.13596947 0.40902472 0.27240364 0.34825922 0.35778758 0.7484867 ]


In [17]:
# arange
# 1. 파라미터 1개
arr1 = np.arange(6)
print(arr1)

# 2. 파라미터 2개
# arange(n, m) : nㅂ터 m-1까지의 연속된 수
arr2 = np.arange(2, 7)
print(arr2)

# 3. 파라미터 3개
# arange(n, m, k) : n부터 m-1까지의 수 중 간격이 k인 수
arr3 = np.arange(3, 17, 3)
print(arr3)

[0 1 2 3 4 5]
[2 3 4 5 6]
[ 3  6  9 12 15]


In [2]:
import numpy as np

arr = np.arange(1, 101)

# 배열 출력
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
arr2 = np.arange(3, 101, 3)

arr2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### 인덱싱, 슬라이싱

In [6]:
arr[0]

1

In [7]:
arr2[1]

6

In [8]:
arr[-1]

100

In [9]:
arr[-2]

99

In [10]:
arr[[1, 3, 4]]

array([2, 4, 5])

In [12]:
arr3 = np.array([2,1,3])

In [13]:
arr[arr3]

array([3, 2, 4])

In [14]:
arr[2:7]

array([3, 4, 5, 6, 7])

In [15]:
arr[0:7]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
arr[2:]

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [18]:
arr[2:6:2]

array([3, 5])

In [19]:
arr[1:10:1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[1:10:3]

array([2, 5, 8])

### numpy 기본연산

In [22]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [23]:
array1 *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
array2 / 3

array([3.33333333, 3.66666667, 4.        , 4.33333333, 4.66666667,
       5.        , 5.33333333, 5.66666667, 6.        , 6.33333333])

In [26]:
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [27]:
array1*array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [28]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [34]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170
    000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

won_array = np.multiply(revenue_in_yen, 10.08)

# 정답 출력
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

In [35]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.
yen_arr = np.array(revenue_in_yen)
dollar_arr = np.array(revenue_in_dollar)

won_array = yen_arr*10.08 + dollar_arr*1138

# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

### numpy 불린 연산

In [36]:
arr1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [37]:
arr1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [38]:
arr1 %2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [39]:
booleans = np.array([True, True, False, False, True])

In [40]:
np.where(booleans) #True인 인덱스만 반환

(array([0, 1, 4], dtype=int64),)

In [41]:
arr1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [42]:
np.where(arr1>4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [43]:
filter = np.where(arr1>4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [45]:
arr1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [46]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
revenue = np.array(revenue_in_yen)
filter = np.where(revenue <= 200000)
bad_days_revenue = revenue[filter]

# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

In [ ]:
import pandas as pd
import numpy as np
    
df = pd.read_csv('data/toeic.csv')

# 코드를 작성하세요.
pass_total = df['LC'] + df['RC'] > 600
pass_both = (df['LC'] >= 250) & ( df['RC'] >= 250)

# 정답 출력
# df
df.loc[pass_total & pass_both] = True
df.loc[(!pass_total) | (!pass_both)] = False
df