In [2]:
import numpy as np

## 06.numpy 행렬 연습

In [3]:

A = np.array([
    [0, 1, -1],
    [1, 2, 3],
    [2, 1, 0],
    [-1, 2, -4]
])
A

array([[ 0,  1, -1],
       [ 1,  2,  3],
       [ 2,  1,  0],
       [-1,  2, -4]])

In [4]:
B = np.array([
    [0, 2],
    [1, 1], 
    [-1, -2]
])
B

array([[ 0,  2],
       [ 1,  1],
       [-1, -2]])

In [10]:
A[1, 1]

-1

In [11]:
A[3, 0]

-1

## 14. numpy로 행렬 연산 연습하기

In [13]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

In [18]:
(2 * A)+ -1 * B  (3 * C + D)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [28]:
-1 * B

array([[ 0, -1],
       [ 1, -1],
       [-5, -2]])

In [29]:
2 * A

array([[ 2, -2,  4],
       [ 6,  4,  4]])

In [31]:
np.dot(2 * A, -1 * B)

array([[-22,  -8],
       [-16, -18]])

In [32]:
np.dot(np.dot(2 * A, -1 * B), 3 * C + D)

array([[  34,  -28],
       [ 110, -130]])

## 18. numpy로 전치, 단위, 역행렬 연습

In [33]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2]
])

B = np.array([
    [0, 1],
    [-1, 1],
    [5, 2]
])

C = np.array([
    [2, -1],
    [-3, 3]
])

D = np.array([
    [-5, 1],
    [2, 0]
])

In [34]:
A_transpose = A.T # 전치행렬
B_transpose = B.T # 전치행렬
C_reverse = np.linalg.pinv(C) # 역행렬
D_transpose = D.T # 전치행렬

In [35]:
result = B_transpose @ (2 * A_transpose) @ (3 * C_reverse + D_transpose)
result

array([[20., 98.],
       [56., 60.]])

## 15. 선형 회귀 가설 함수(H) 구현

In [36]:
import numpy as np

def prediction(theta_0, theta_1, x):
    """주어진 학습 데이터 벡터 x에 대해서 예측 값을 리턴하는 함수"""
    arr = []
    arr = theta_0 + (theta_1 * x)
    return arr

# 입력 변수(집 크기) 초기화 (모든 집 평수 데이터를 1/10 크기로 줄임)
house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])
theta_0 = -3
theta_1 = 2

prediction(theta_0, theta_1, house_size)

array([-1.2, -0.2,  1. ,  1.2,  2.2,  3.6,  3.7,  4.8,  5.8,  6.4,  7.4,
        8.5, 10.4, 10.8])

## 16. 선형 회귀 예측 오차(MSE) 구현

In [37]:
import numpy as np

def prediction(theta_0, theta_1, x):
    """주어진 학습 데이터 벡터 x에 대해서 모든 예측 값을 벡터로 리턴하는 함수"""
    arr = []
    arr = theta_0 + (theta_1 * x)
    return arr
    

def prediction_difference(theta_0, theta_1, x, y):
    """모든 예측 값들과 목표 변수들의 오차를 벡터로 리턴해주는 함수"""
    vector = []
    vector = prediction(theta_0, theta_1, x) - y
    return vector
    
    
# 입력 변수(집 크기) 초기화 (모든 집 평수 데이터를 1/10 크기로 줄임)
house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])

# 목표 변수(집 가격) 초기화 (모든 집 값 데이터를 1/10 크기로 줄임)
house_price = np.array([0.3, 0.75, 0.45, 1.1, 1.45, 0.9, 1.8, 0.9, 1.5, 2.2, 1.75, 2.3, 2.49, 2.6])

theta_0 = -3
theta_1 = 2

prediction_difference(-3, 2, house_size, house_price)

array([-1.5 , -0.95,  0.55,  0.1 ,  0.75,  2.7 ,  1.9 ,  3.9 ,  4.3 ,
        4.2 ,  5.65,  6.2 ,  7.91,  8.2 ])

## 17. 선형 회귀 경사 하강법 구현

In [38]:
import numpy as np

def prediction(theta_0, theta_1, x):
    """주어진 학습 데이터 벡터 x에 대해서 모든 예측 값을 벡터로 리턴하는 함수"""
    arr = []
    arr = theta_0 + (theta_1 * x)
    return arr
    
    
def prediction_difference(theta_0, theta_1, x, y):
    """모든 예측 값들과 목표 변수들의 오차를 벡터로 리턴해주는 함수"""
    vector = []
    vector = prediction(theta_0, theta_1, x) - y
    return vector
    
    
def gradient_descent(theta_0, theta_1, x, y, iterations, alpha):
    """주어진 theta_0, theta_1 변수들을 경사 하강를 하면서 업데이트 해주는 함수"""
    for _ in range(iterations):  # 정해진 번만큼 경사 하강을 한다
        error = prediction_difference(theta_0, theta_1, x, y)  # 예측값들과 입력 변수들의 오차를 계산
        # 코드를 쓰세요
        theta_0 = theta_0 - alpha * error.mean()
        theta_1 = theta_1 - alpha * (error * x).mean()
    
    return theta_0, theta_1
    
    
# 입력 변수(집 크기) 초기화 (모든 집 평수 데이터를 1/10 크기로 줄임)
house_size = np.array([0.9, 1.4, 2, 2.1, 2.6, 3.3, 3.35, 3.9, 4.4, 4.7, 5.2, 5.75, 6.7, 6.9])

# 목표 변수(집 가격) 초기화 (모든 집 값 데이터를 1/10 크기로 줄임)
house_price = np.array([0.3, 0.75, 0.45, 1.1, 1.45, 0.9, 1.8, 0.9, 1.5, 2.2, 1.75, 2.3, 2.49, 2.6])

# theta 값들 초기화 (아무 값이나 시작함)
theta_0 = 2.5
theta_1 = 0

# 학습률 0.1로 200번 경사 하강
theta_0, theta_1 = gradient_descent(theta_0, theta_1, house_size, house_price, 200, 0.1)

theta_0, theta_1

(0.16821801417752166, 0.3438032402351198)

## 25. 범죄율로 집 값 예측하기

In [39]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd  

# 보스턴 집 데이터 갖고 오기
boston_house_dataset = datasets.load_boston()

# 입력 변수를 사용하기 편하게 pandas dataframe으로 변환
X = pd.DataFrame(boston_house_dataset.data, columns=boston_house_dataset.feature_names)

# 목표 변수를 사용하기 편하게 pandas dataframe으로 변환
y = pd.DataFrame(boston_house_dataset.target, columns=['MEDV'])

# 1. 범죄율 열만 선택
x = X[['CRIM']]

# 2. traing-test set 나누기
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

# 3. 모델 생성/학습/
model = LinearRegression()
model.fit(x_train, y_train) 
y_test_predict = model.predict(x_test)  # 예측 값 벡터 변수

# 테스트 코드 (평균 제곱근 오차로 모델 성능 평가)
mse = mean_squared_error(y_test, y_test_predict)
mse ** 0.5



8.180697228317348

## 09. 다중 선형 회귀 가설 함수 구현

In [40]:
import numpy as np

def prediction(X, theta):
    """다중 선형 회귀 가정 함수. 모든 데이터에 대한 예측 값을 numpy 배열로 리턴한다"""
    # 코드를 쓰세요
    return X@theta
    
# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 파라미터 theta 값 정의
theta = np.array([1, 2, 3, 4])

prediction(X, theta)

array([22. , 21.8, 21.2, 26.7, 24.7, 24.8, 25.5, 26.2, 29.7, 31.4, 33.1,
       33.9, 39. , 39.4, 39.5, 40. ])

## 10. 다중 선형 회귀 경사 하강법 구현

In [41]:
import numpy as np

def prediction(X, theta):
    """다중 선형 회귀 가정 함수. 모든 데이터에 대한 예측 값을 numpy 배열로 리턴한다"""
    # 전 과제 코드를 갖고 오세요
    return X@theta

def gradient_descent(X, theta, y, iterations, alpha):
    """다중 선형 회귀 경사 하강법을 구현한 함수"""
    m = len(X)  # 입력 변수 개수 저장
    
    for i in range(iterations):
        error = prediction(X, theta) - y
        theta = theta - alpha / m * (X.T @ error)
    return theta
    

# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 목표 변수
house_price = np.array([3, 3.2, 3.6 , 8, 3.4, 4.5, 5, 5.8, 6, 6.5, 9, 9, 10, 12, 13, 15])  # 집 가격

# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 입력 변수 y 정의
y = house_price

# 파라미터 theta 초기화
theta = np.array([0, 0, 0, 0])

# 학습률 0.01로 100번 경사 하강
theta = gradient_descent(X, theta, y, 100, 0.01)

theta

array([0.11484521, 1.21120425, 0.18270523, 0.30060782])

## 13. 다중 선형 회귀 정규 방정식 구현

In [42]:
import numpy as np

def normal_equation(X, y):
    """설계 행렬 X와 목표 변수 벡터 y를 받아 정규 방정식으로 최적의 theta를 구하는 함수"""

    theta = np.linalg.pinv(X.T @ X) @ X.T @ y
    return theta
    
# 입력 변수
house_size = np.array([1.0, 1.5, 1.8, 5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0, 8.0, 8.5, 9.0, 10.0])  # 집 크기
distance_from_station = np.array([5, 4.6, 4.2, 3.9, 3.9, 3.6, 3.5, 3.4, 2.9, 2.8, 2.7, 2.3, 2.0, 1.8, 1.5, 1.0])  # 지하철역으로부터의 거리 (km)
number_of_rooms = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])  # 방 수

# 목표 변수
house_price = np.array([3, 3.2, 3.6 , 8, 3.4, 4.5, 5, 5.8, 6, 6.5, 9, 9, 10, 12, 13, 15])  # 집 가격

# 입력 변수 파라미터 X 정의
X = np.array([
    np.ones(16),
    house_size,
    distance_from_station,
    number_of_rooms
]).T

# 입력 변수 y 정의
y = house_price

# 정규 방적식으로 theta 계산
theta = normal_equation(X, y)
theta

array([ 5.24706322,  1.30727421, -0.68881811, -0.8709494 ])

## 18. scikit-learn으로 당뇨 수치 예측하기

In [1]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd  

In [3]:
# 당뇨병 데이터 갖고 오기
diabetes_dataset = datasets.load_diabetes()

# 데이터 확인
print(diabetes_dataset.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, T-Cells (a type of white blood cells)
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, thyroid stimulating hormone
      - s5      ltg, lamotrigine
      - s6      glu, blood sugar level

Note: Each of these 10 feature va

In [4]:
# 입력 변수를 사용하기 편하게 pandas dataframe으로 변환
X = pd.DataFrame(diabetes_dataset.data, columns=diabetes_dataset.feature_names)

# 목표 변수를 사용하기 편하게 pandas dataframe으로 변환
y = pd.DataFrame(diabetes_dataset.target, columns=['diabetes'])

# 코드를 쓰세요
# 1. 데이터를 training/test 셋으로 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

# 2. 선형 회귀 모델을 학습
model = LinearRegression()
model.fit(X_train, y_train)

# 3. 학습시킨 데이터를 이용해서 예측
y_test_predict = model.predict(X_test)

# 평균 제곱 오차의 루트를 통해서 테스트 데이터에서의 모델 성능 판단
mse = mean_squared_error(y_test, y_test_predict)

mse ** 0.5

54.60389611984443

## 10. 다항 회귀로 당뇨병 예측하기 1 (문제 생성)

In [5]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd  

In [6]:
diabetes_dataset = datasets.load_diabetes()  # 데이터 셋 갖고오기

In [9]:
# 코드를 쓰세요
diabetes_dataset.data  # dataset 확인

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [10]:
diabetes_dataset.data.shape

(442, 10)

In [11]:
diabetes_dataset.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [13]:
polynomial_transformer = PolynomialFeatures(2)
polynomial_transformer

PolynomialFeatures()

In [14]:
polynomial_data = polynomial_transformer.fit_transform(diabetes_dataset.data)

In [15]:
polynomial_data

array([[ 1.00000000e+00,  3.80759064e-02,  5.06801187e-02, ...,
         3.96345222e-04, -3.51306487e-04,  3.11385733e-04],
       [ 1.00000000e+00, -1.88201653e-03, -4.46416365e-02, ...,
         4.66895386e-03,  6.30027907e-03,  8.50158677e-03],
       [ 1.00000000e+00,  8.52989063e-02,  5.06801187e-02, ...,
         8.20118159e-06, -7.42585403e-05,  6.72382480e-04],
       ...,
       [ 1.00000000e+00,  4.17084449e-02,  5.06801187e-02, ...,
         2.19768591e-03, -7.26197419e-04,  2.39962721e-04],
       [ 1.00000000e+00, -4.54724779e-02, -4.46416365e-02, ...,
         1.98277609e-03, -1.15463583e-03,  6.72382480e-04],
       [ 1.00000000e+00, -4.54724779e-02, -4.46416365e-02, ...,
         1.78072159e-05, -1.29313778e-05,  9.39060506e-06]])

In [16]:
polynomial_data.shape

(442, 66)

In [17]:
polynomial_feature_names = polynomial_transformer.get_feature_names(diabetes_dataset.feature_names)

In [18]:
polynomial_feature_names

['1',
 'age',
 'sex',
 'bmi',
 'bp',
 's1',
 's2',
 's3',
 's4',
 's5',
 's6',
 'age^2',
 'age sex',
 'age bmi',
 'age bp',
 'age s1',
 'age s2',
 'age s3',
 'age s4',
 'age s5',
 'age s6',
 'sex^2',
 'sex bmi',
 'sex bp',
 'sex s1',
 'sex s2',
 'sex s3',
 'sex s4',
 'sex s5',
 'sex s6',
 'bmi^2',
 'bmi bp',
 'bmi s1',
 'bmi s2',
 'bmi s3',
 'bmi s4',
 'bmi s5',
 'bmi s6',
 'bp^2',
 'bp s1',
 'bp s2',
 'bp s3',
 'bp s4',
 'bp s5',
 'bp s6',
 's1^2',
 's1 s2',
 's1 s3',
 's1 s4',
 's1 s5',
 's1 s6',
 's2^2',
 's2 s3',
 's2 s4',
 's2 s5',
 's2 s6',
 's3^2',
 's3 s4',
 's3 s5',
 's3 s6',
 's4^2',
 's4 s5',
 's4 s6',
 's5^2',
 's5 s6',
 's6^2']

In [19]:
X = pd.DataFrame(polynomial_data, columns=polynomial_feature_names)

In [20]:
# 테스트 코드
X.head()

1       age       sex       bmi        bp        s1        s2        s3  \
0  1.0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1  1.0 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  1.0  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3  1.0 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  1.0  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5  ...      s3^2     s3 s4     s3 s5     s3 s6      s4^2  \
0 -0.002592  0.019908  ...  0.001884  0.000113 -0.000864  0.000766  0.000007   
1 -0.039493 -0.068330  ...  0.005537 -0.002939 -0.005085 -0.006861  0.001560   
2 -0.002592  0.002864  ...  0.001047  0.000084 -0.000093  0.000839  0.000007   
3  0.034309  0.022692  ...  0.001299 -0.001236 -0.000818  0.000337  0.001177   
4 -0.002592 -0.031991  ...  0.000066 -0.000021 -0.000260 -0.000380  0.000007   

      s4 s5     s4 s6      s5^2     s5 s6      s6^2  
0 -0.000052  0.000046  0.000396 -0.000351  0.000311  
1  0.002699  0.003641  0.004669  0.006300  0.008502  
2 -0.000007  0.000067  0.000008 -0.000074  0.000672  
3  0.000779 -0.000321  0.000515 -0.000212  0.000088  
4  0.000083  0.000121  0.001023  0.001492  0.002175  

[5 rows x 66 columns]

## 11. 다항 회귀로 당뇨병 예측하기 (2) 모델 학습

In [21]:
# 필요한 라이브러리 import
from sklearn import datasets
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import pandas as pd 

In [22]:
diabetes_dataset = datasets.load_diabetes()

In [23]:
polynomial_transformer = PolynomialFeatures(2)
polynomial_data = polynomial_transformer.fit_transform(diabetes_dataset.data)
polynomial_feature_names = polynomial_transformer.get_feature_names(diabetes_dataset.feature_names)
X = pd.DataFrame(polynomial_data, columns=polynomial_feature_names)

In [24]:
# 목표 변수
y = pd.DataFrame(diabetes_dataset.target, columns=['diabetes'])

In [25]:
# 1. 데이터를 training / test set으로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [26]:
#  2. 선형 회귀 모델을 가져와서, training set 데이터를 사용하여 학습
model = LinearRegression() # 모델 생성
model.fit(X_train, y_train) # 학습

LinearRegression()

In [27]:
# 3. test set 데이터를 이용해서 학습시킨 모델로 예측
y_test_predict = model.predict(X_test)

In [28]:
# 결과 확인
mse = mean_squared_error(y_test, y_test_predict)
mse ** 0.5

57.87704902724896

## 16. 로지스틱 회귀 가정 함수 구현

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    """시그모이드 함수"""
    return 1 / (1 + np.exp(-x))

In [8]:
def prediction(X, theta):
    """로지스틱 회귀 가정 함수"""
    return sigmoid(X @ theta)

In [12]:
# 입력 변수
hours_studied = np.array([0.2, 0.3, 0.7, 1, 1.3, 1.8, 2, 2.1, 2.2, 3, 4, 4.2, 4, 4.7, 5.0, 5.9])  # 공부 시간 (단위: 100시간)
gpa_rank = np.array([0.9, 0.95, 0.8, 0.82, 0.7, 0.6, 0.55, 0.67, 0.4, 0.3, 0.2, 0.2, 0.15, 0.18, 0.15, 0.05]) # 학년 내신 (백분률)
number_of_tries = np.array([1, 2, 2, 2, 4, 2, 2, 2, 3, 3, 3, 3, 2, 4, 1, 2])  # 시험 응시 횟수

# 목표 변수
passed = np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])  # 시험 통과 여부 (0: 탈락, 1:통과)

In [5]:
# 설계 행렬 X 정의
X = np.array([
    np.ones(16),
    hours_studied,
    gpa_rank,
    number_of_tries
]).T

In [6]:
# 파라미터 theta 정의
theta = [0.5, 0.3, -2, 0.2]  

In [9]:
prediction(X, theta)

array([0.26114999, 0.28699984, 0.37989357, 0.39174097, 0.57199613,
       0.55971365, 0.59868766, 0.54735762, 0.72312181, 0.80218389,
       0.86989153, 0.87653295, 0.85814894, 0.91293423, 0.86989153,
       0.9289057 ])

## 17. 로지스틱 회귀 경사 하강법 구현

In [15]:
def gradient_descent(X, theta, y, iterations, alpha):
    """로지스틱 회귀 경사 하강 알고리즘"""
    m = len(X)  # 입력 변수 개수 저장

    for _ in range(iterations):
        # 코드를 쓰세요
        error = prediction(X, theta) - y
        theta = theta - alpha * 1/m * (X.T @ error)
        
    return theta

In [13]:
# 입력 변수 y 정의
y = passed

In [16]:
theta = [0, 0, 0, 0]  # 파라미터 초기값 설정
theta = gradient_descent(X, theta, y, 300, 0.1)  # 경사 하강법을 사용해서 최적의 파라미터를 찾는다
theta

array([-1.35280508,  1.61640725, -1.83666046, -0.60286277])

## 23. 로지스틱 회귀로 와인 종류 분류

In [17]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import pandas as pd  

In [18]:
wine_data = datasets.load_wine()
# 데이터 셋을 살펴보는 코드
print(wine_data.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [19]:
# 입력 변수를 사용하기 편하게 pandas dataframe으로 변환
X = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

In [20]:
X

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [21]:
# 목표 변수를 사용하기 편하게 pandas dataframe으로 변환
y = pd.DataFrame(wine_data.target, columns=['Y/N'])

In [22]:
y

Y/N
0      0
1      0
2      0
3      0
4      0
..   ...
173    2
174    2
175    2
176    2
177    2

[178 rows x 1 columns]

In [25]:
# 1. train/test dataset으로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

# 2. LogisticRegression 모델 생성 및 학습
y_train = y_train.values.ravel()  # 로지스틱 회귀에서는 작성하는 걸 추천
logistic_model = LogisticRegression(solver='saga', max_iter = 7500)
logistic_model.fit(X_train, y_train)

# 3. 학습시킨 모델을 이용하여 test set 데이터에 대해 예측
y_test_predict = logistic_model.predict(X_test)

In [26]:
# 테스트 코드
score = logistic_model.score(X_test, y_test)
y_test_predict, score

(array([0, 1, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2]),
 0.75)

## 09. Normalization 직접하기

In [27]:
# 필요한 도구 임포트
from sklearn import preprocessing
import pandas as pd

In [28]:
PATIENT_FILE_PATH = 'datasets/liver_patient_data.csv'
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [29]:
# 데이터 파일을 pandas dataframe으로 가지고 온다
liver_patients_df = pd.read_csv(PATIENT_FILE_PATH)

FileNotFoundError: [Errno 2] File datasets/liver_patient_data.csv does not exist: 'datasets/liver_patient_data.csv'

## 14. One-hot Encoding 직접 해보기

In [30]:
import pandas as pd

GENDER_FILE_PATH = './datasets/gender.csv'

gender_df = pd.read_csv(GENDER_FILE_PATH)
input_data = gender_df.drop(['Gender'], axis=1)

# 여기 코드를 쓰세요
X = pd.get_dummies(data=input_data  )

# 체점용 코드
X.head()

FileNotFoundError: [Errno 2] File ./datasets/gender.csv does not exist: './datasets/gender.csv'

## 13. 질문 노트 평가하기

In [2]:
def Geni(class_1, class_2):
    class_1_per = class_1 / (class_1 + class_2)
    class_2_per = class_2 / (class_1 + class_2)
    
    result_1 = 1 - (class_1_per ** 2) - (class_2_per ** 2)
    result_2 = class_1 + class_2

    return result_1, result_2
    
def node_result(geni_1, geni_1_2, total_1, total_2):
    return round((total_1 * geni_1 + total_2 * geni_2) / (total_1 + total_2), 3)

geni_1, total_1 = Geni(15, 80)
geni_2, total_2 = Geni(90, 0)

print(node_result(geni_1, geni_2, total_1, total_2))

0.137


## 22. 유방암 데이터 준비하기 (Decision Tree)

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

import pandas as pd

# 데이터 셋 불러 오기
cancer_data = load_breast_cancer()
# 데이터 셋을 살펴보기 위한 코드
# print(cancer_data.DESCR)

# 코드를 쓰세요
X = pd.DataFrame(cancer_data.data, columns = cancer_data.feature_names)
y = pd.DataFrame(cancer_data.target, columns = ['class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

# 실행 코드
X_train.head()

## 23. 결정 트리로 악성/양성 유방암 분류하기 (Decision Tree)

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

import pandas as pd

# 데이터 셋 불러 오기
cancer_data = load_breast_cancer()

X = pd.DataFrame(cancer_data.data, columns = cancer_data.feature_names)
y = pd.DataFrame(cancer_data.target, columns = ['class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

# 코드를 쓰세요
model = DecisionTreeClassifier(max_depth=5, random_state=42) # 모델 생성
model.fit(X_train, y_train) # 모델 학습
predictions = model.predict(X_test) # 결과 예측
score = model.score(X_test, y_test)


# 출력 코드
predictions, score

## 12. 에다 부스트로 악성/양성 유방암 분류하기

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier

import pandas as pd

# 데이터 셋 불러 오기
cancer_data = load_breast_cancer()

# 챕터 1 유방암 데이터 준비하기 과제에서 쓴 코드를 갖고 오세요
X = pd.DataFrame(cancer_data.data, columns = cancer_data.feature_names)
y = pd.DataFrame(cancer_data.target, columns = ['class'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

# 코드를 쓰세요
model = AdaBoostClassifier(n_estimators=50, random_state=5)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
score = model.score(X_test, y_test)

# 출력 코드
predictions, score