# 가장 큰 제목
## 두번째 큰 제목
### 세번째 큰 제목

이렇게...

글을 **두껍게** 쓸 수도... *날려*쓰기도 가능

리스트
* items
* items2
* items3

In [5]:
x =17

In [6]:
x

17

In [7]:
print(2 + 5)
print(x)
print(3 * 4)

7
17
12


In [8]:
import numpy

In [9]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [10]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [11]:
type(array1)

numpy.ndarray

In [12]:
array1.shape

(11,)

In [14]:
array2=numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [15]:
array2.shape

(3, 4)

In [16]:
array1.size

11

In [17]:
array2.size

12

In [18]:
import numpy as np

array1 = np.full(6, 0)
array2 = np.zeros(6)

In [19]:
array1

array([0, 0, 0, 0, 0, 0])

In [20]:
array2

array([0., 0., 0., 0., 0., 0.])